language: python

python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email:
    on_success: change
    on_failure: always

sudo: false